### ISSUE TITLE
 Bullet points

### ISSUE THREAD

**Issue by Silberengel** [fiatjaf/svelte-asciidoc#1]
I've been trying to edit my Wiki documents, so that they display nicely in markdown or asciidoc, and I can't figure out why bullet points as asterix aren't displaying well under asciidoc.

Example
https://wikistr.com/nkbip-01*dd664d5e4016433a8cd69f005ae1480804351789b59de5af06276de65633d319

**Comment by fiatjaf** [comment]
Turns out you need a blank line between the list bullet points and the previous and next paragraphs, I just realized. I should add a preview thing on https://wikistr.com/.

**Comment by fiatjaf** [comment]
Deployed.

**Comment by fiatjaf** [comment]
Next I have to fix quill-asciidoc to account for these shenanigans.

**Comment by Silberengel** [comment]
Looks good now, thanks.
