### ISSUE TITLE
Special characters render as code

### ISSUE THREAD

**Issue by Silberengel** [fiatjaf/svelte-asciidoc#2]
I've noticed in a few wiki pages, that some characters render as &#etc. 

Example at the bottom of [this one](https://wikistr.com/nkbip-01*dd664d5e4016433a8cd69f005ae1480804351789b59de5af06276de65633d319) or [this one](https://wikistr.com/hypernote-nip*a9434ee165ed01b286becfc2771ef1705d3537d051b387288898cc00d5c885be).

**Comment by Silberengel** [comment]
It's the apostrophes. All apostrophes come out as attestor&#8217;s

**Comment by Silberengel** [comment]
Also, elipses like "..."

**Comment by fiatjaf** [comment]
Thank you for the reports. Please let me know if you find more ocurrences. This seems to be a bug in the Asciidoc parser, it escapes some characters in seemingly random instances, not following any reasonable pattern, so the solution was to track down these ocurrences and patch them.

**Comment by Silberengel** [comment]
Looks good, thanks! 🫂

**Comment by Silberengel** [comment]
I found some more:

&#8201 &#8212

Maybe find some way to look for "&#"?

From https://wikistr.com/gc-alexandria*dd664d5e4016433a8cd69f005ae1480804351789b59de5af06276de65633d319

**Comment by fiatjaf** [comment]
Thank you. It's so weird. That was supposed to be a `--`, but it gets transformed into `—` and then garbled.

I tried a bunch of other characters from here: https://www.w3.org/wiki/Common_HTML_entities_used_for_typography
But nothing seems to yield problems.

**Comment by Silberengel** [comment]
I had the same problem, developing my own client that involves downloading some RSS feed. 🤷🏻‍♀️ Comes in with these weird characters.
