### ISSUE TITLE
Links not rendering within a table

### ISSUE THREAD

**Issue by Silberengel** [fiatjaf/svelte-asciidoc#3]
I couldn't get the hyperlinks to work within the right-hand column of the table. The HTML is simply displayed.

This is a screenshot from Wikifreedia, but it's the same on Wikistr.
[Nostr-Event-Register](https://wikistr.com/nostr-event-register*dd664d5e4016433a8cd69f005ae1480804351789b59de5af06276de65633d319)

![example of error in display](https://i.nostr.build/JjQ6aYxcVshxCYie.png)

**Comment by Silberengel** [comment]
Anytime there is Asciidoc markup in a column, you can just put "a" in the column description (at the top of the table) and it'll render correctly. Took me hours to figure it out.

Unfortunately, the clicking the link doesn't take me anywhere.

**Comment by fiatjaf** [comment]
There is at least one other bug with these tables, they're being rendered without a `<table>` HTML element so they look all broken.

**Comment by Silberengel** [comment]
Maybe that's why the HTML within the tables is messed up.

**Comment by fiatjaf** [comment]
Should be working on wikistr.com now.

**Comment by Silberengel** [comment]
Seems to be fine, now. Thanks!
